[GENERAl]
BROWSER = "CHROME"
ELEMENT_OUTPUT_LOG = "user_friendly"
DO_NOT_RESTART = true
SOFT_RESTART = false

[CUSTOM]
USER_LOGIN = "Proverka95"
USER_PASSWORD = "Proverka11"
SBIS_SITE = "https://fix-online.sbis.ru/"
USER_MESSAGE = "Дай денег"
USER_NAME = "Вилинский Андрей Александрович"
FOLDER_NAME = "Новая папка"

TASK_DATE = "14.01.25"
TASK_DATE_FULL = "14 янв, вт"
TASK_NUM = "1"
TASK_EXECUTOR = "Балкова А.А."
TASK_AUTHOR = "Вилинский А.А."
TASK_DESCRIPTION = "ЭТАЛОННАЯ ЗАДАЧА , не удалять!"
TASK_LINK = "https://fix-online.sbis.ru/doc/18724c73-21c9-4b18-9d26-d4ffac2317b9?client=6923295"