[GENERAl]
BROWSER = "CHROME"
ELEMENT_OUTPUT_LOG = "user_friendly"
DO_NOT_RESTART = true
SOFT_RESTART = false

[CUSTOM]
USER_LOGIN = "Proverka95"
USER_PASSWORD = "Proverka11"
SBIS_SITE = "https://fix-online.sbis.ru/"
USER_MESSAGE = 'Дай денег'
USER_NAME = 'Вилинский Андрей Александрович'